SELECT   D.DNAME AS Department, count(E.SSN) AS CountEmp
FROM EMPLOYEE AS E
JOIN DEPARTMENT AS D
  ON E.DNO = D.DNUMBER
JOIN (
    SELECT D.DNUMBER AS DNUMBER
    FROM EMPLOYEE AS E
    JOIN DEPARTMENT AS D
      ON E.DNO = D.DNUMBER
    GROUP BY D.DNUMBER
    HAVING count(E.SSN) > 2
    ) AS DNUMBERg2
  ON DNUMBERg2.DNUMBER = D.DNUMBER
WHERE E.SALARY > 4000
GROUP BY D.DNUMBER;
