SELECT @max_d5 := MAX(E.SALARY)
FROM EMPLOYEE AS E
JOIN DEPARTMENT AS D
  ON E.DNO = D.DNUMBER
WHERE D.DNUMBER = 5
ORDER BY E.FNAME ASC;

SELECT E.FNAME, E.LNAME
FROM EMPLOYEE AS E
WHERE E.SALARY > @max_d5;
